CREATE TABLE POKEMON (
    ID   INTEGER NOT NULL AUTO_INCREMENT,
    POKEMON_NAME VARCHAR(128) NOT NULL,
    BASE_EXPERIENCE INTEGER NOT NULL,
    HEIGHT INTEGER NOT NULL,
    IS_DEFAULT INTEGER NOT NULL,
    POKEMON_ORDER INTEGER NOT NULL,
    WEIGHT INTEGER NOT NULL,
    TYPES VARCHAR (512) NOT NULL,
    PRIMARY KEY (id)
);